apiVersion: v1
kind: Service
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  ports:
    - port: 8069
      targetPort: 8069
      nodePort: 30000
  selector:
    app: odoo
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odo-pv-claim
  labels:
    app: odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels: 
    app:  odoo
spec:
  selector:
    matchLabels:
      app: odoo
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo
        tier: frontend
    spec:
      containers:
        - image: odoo:18.0
          name: odoo
          env:
          - name: PASSWORD
            value: Car123
          - name: USER
            value: carlos
          - name: HOST
            value: odoo-postgres
          ports:
          - containerPort: 8069
            name: odoo
          volumeMounts:
          - name: odoo-persistent-storage
            mountPath: /var/lib/odoo
      volumes:
      - name: odoo-persistent-storage
        persistentVolumeClaim:
          claimName: odo-pv-claim
